version: "3.9"

services:

  tarifas-db:
    image: postgres:15
    container_name: tarifas-db
    restart: always
    environment:
      POSTGRES_DB: tarifasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"   # puerto expuesto externo -> interno
    volumes:
      - tarifas_data:/var/lib/postgresql/data
    networks:
      - tarifas-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-tarifas
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"     # pgAdmin web
    depends_on:
      - tarifas-db
    networks:
      - tarifas-net

  ms-tarifas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-tarifas
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker    # usa application-docker.properties
    ports:
      - "8083:8083"
    depends_on:
      - tarifas-db
    networks:
      - tarifas-net

volumes:
  tarifas_data:

networks:
  tarifas-net:
    driver: bridge
